# Generated by Django 6.0.1 on 2026-01-18 21:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Nome")),
                (
                    "category_type",
                    models.CharField(
                        choices=[("income", "Receita"), ("expense", "Despesa")],
                        max_length=10,
                        verbose_name="Tipo",
                    ),
                ),
                (
                    "color",
                    models.CharField(
                        default="#6b7280",
                        help_text="Cor em formato hexadecimal (ex: #6b7280)",
                        max_length=7,
                        verbose_name="Cor",
                    ),
                ),
                (
                    "is_default",
                    models.BooleanField(
                        default=False,
                        help_text="Categorias padrão não podem ser excluídas",
                        verbose_name="Categoria padrão",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="categories",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuário",
                    ),
                ),
            ],
            options={
                "verbose_name": "Categoria",
                "verbose_name_plural": "Categorias",
                "ordering": ["name"],
                "indexes": [
                    models.Index(
                        fields=["user", "category_type"],
                        name="categories__user_id_f0c68e_idx",
                    )
                ],
                "unique_together": {("user", "name")},
            },
        ),
    ]
